spring.application.name=backend

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/omnibook
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:uplrieh3}
cloudinary.api-key=${CLOUDINARY_API_KEY:324628571863774}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:-Mc4Bx8PliP4fUz6R2g3JeuCm7s}
